name: keyboardpopper
description: A Flutter package that simplifies keyboard dismissal through intuitive gestures.
version: 0.0.1
homepage: https://github.com/pandey407/keyboardpopper

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
